---
- hosts: ec2
  tasks:
    - include_vars:
        file: ansible_variables.yml
        name: var

    - file:
        path: /home/{{ var.user }}/all/wiki/code
        state: directory
        mode: "0755"

    - git:
        repo: "https://otokki2100@github.com/otokki2100/{{ item }}.git"
        dest: "{{ var.wiki_code_path_remote }}/{{ item }}"
      with_items:
        - cloud-aws
        - svc-iac
        - svc-web
        - svc-conn
        - svc-repo
        - lang-code

    - ansible.builtin.shell:
        cmd: sh {{ var.wiki_code_path_remote }}/{{ code }} {{ var.user }} {{ var.dist }} {{ var.domain }}
